#!/bin/bash

echo "=========================================="
echo "Check What Code is Actually Deployed"
echo "=========================================="
echo ""

echo "Run this on your EC2 server:"
echo ""
echo "cd /var/www/moneyone/moneyone/backend"
echo ""
echo "# Check if the NEW validation code exists:"
echo "grep -n 'Get actual wallet balance from merchant_wallet table' payout_routes.py"
echo ""
echo "# If nothing found, check for OLD code:"
echo "grep -n 'Get wallet balance from approved fund requests' payout_routes.py"
echo ""
echo "# Check the exact validation logic around line 1130-1170:"
echo "sed -n '1130,1170p' payout_routes.py"
echo ""
echo "=========================================="
echo "Expected NEW Code (should see):"
echo "=========================================="
echo "# Get actual wallet balance from merchant_wallet table"
echo "cursor.execute(\"\"\""
echo "    SELECT balance FROM merchant_wallet WHERE merchant_id = %s"
echo "\"\"\", (merchant_id,))"
echo ""
echo "=========================================="
echo "OLD Code (should NOT see):"
echo "=========================================="
echo "# Get wallet balance from approved fund requests"
echo "cursor.execute(\"\"\""
echo "    SELECT COALESCE(SUM(amount), 0) as wallet_balance"
echo "    FROM fund_requests"
echo ""
