#!/usr/bin/env python3
"""
Test script for new SkrillPe API integration
Tests the updated endpoint: /api/skrill/upi/qr/send/intent/WL
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from skrillpe_service import skrillpe_service
import json
import time

def test_new_skrillpe_api():
    """Test the new SkrillPe API endpoint"""
    print("🧪 Testing New SkrillPe API Integration")
    print("=" * 50)
    
    # Test merchant ID (use existing merchant)
    test_merchant_id = "9000000001"
    
    # Test order data
    test_order = {
        'amount': '100.00',
        'orderid': 'TEST_ORDER_' + str(int(time.time())),
        'payee_fname': 'Test',
        'payee_lname': 'Customer',
        'payee_mobile': '9876543210',
        'payee_email': 'test@example.com'
    }
    
    print(f"📋 Test Order Data:")
    print(json.dumps(test_order, indent=2))
    print()
    
    # Test the new API
    print("🚀 Calling new SkrillPe API...")
    result = skrillpe_service.create_payin_order(test_merchant_id, test_order)
    
    print("📊 API Response:")
    print(json.dumps(result, indent=2, default=str))
    
    if result.get('success'):
        print("\n✅ New SkrillPe API integration successful!")
        print(f"Transaction ID: {result.get('txn_id')}")
        print(f"PG Transaction ID: {result.get('pg_txn_id')}")
        print(f"Status: {result.get('status')}")
        print(f"Intent URL: {result.get('intent_url')}")
        print(f"Tiny URL: {result.get('tiny_url')}")
        
        # Test status check if transaction was created
        if result.get('txn_id'):
            print("\n🔍 Testing status check...")
            status_result = skrillpe_service.check_payment_status(result['txn_id'])
            print("Status Check Result:")
            print(json.dumps(status_result, indent=2, default=str))
    else:
        print("\n❌ API integration failed!")
        print(f"Error: {result.get('message')}")
    
    return result

def compare_api_changes():
    """Compare old vs new API structure"""
    print("\n📋 API Changes Summary:")
    print("=" * 50)
    
    print("🔄 Endpoint Change:")
    print("  Old: /api/skrill/au/dynamicqr/WL")
    print("  New: /api/skrill/upi/qr/send/intent/WL")
    
    print("\n📦 Payload Changes:")
    print("  Removed fields:")
    print("    - vpa")
    print("    - customerName") 
    print("    - remark")
    
    print("  Kept fields:")
    print("    - transactionId (mapped from txn_id)")
    print("    - amount (from order amount)")
    print("    - customerNumber (mapped from payee_mobile)")
    print("    - CompanyAlise (from config)")
    
    print("\n📤 Response Changes:")
    print("  Old response fields:")
    print("    - status, qrPath, id, vpa")
    print("  New response fields:")
    print("    - code, reason, intentUrl, tinyUrl")
    
    print("\n✨ Benefits:")
    print("  - Simplified payload structure")
    print("  - Direct UPI intent URLs (no QR decoding needed)")
    print("  - Better mobile app integration")
    print("  - Shorter URLs with tinyUrl option")

def show_field_mapping():
    """Show exact field mapping"""
    print("\n🗺️  Field Mapping:")
    print("=" * 50)
    
    mapping = {
        "transactionId": "txn_id (generated by generate_txn_id())",
        "amount": "amount (from order_data)",
        "customerNumber": "payee_mobile (from order_data)",
        "CompanyAlise": "company_alias (from config)"
    }
    
    for new_field, source in mapping.items():
        print(f"  {new_field:15} ← {source}")
    
    print("\n📥 Response Mapping:")
    response_mapping = {
        "code": "pg_txn_id (transaction reference)",
        "reason": "error message (if failed)",
        "intentUrl": "qr_string/upi_link (UPI payment URL)",
        "tinyUrl": "remarks (shortened URL)"
    }
    
    for response_field, usage in response_mapping.items():
        print(f"  {response_field:15} → {usage}")

if __name__ == "__main__":
    try:
        # Show field mapping
        show_field_mapping()
        
        # Show API changes
        compare_api_changes()
        
        # Test the new API
        test_result = test_new_skrillpe_api()
        
        print("\n" + "=" * 50)
        print("🎯 Test Summary:")
        if test_result.get('success'):
            print("✅ New SkrillPe API integration is working correctly!")
            print("🔗 UPI Intent URL generated successfully")
        else:
            print("❌ Integration needs attention")
            print(f"Issue: {test_result.get('message', 'Unknown error')}")
            
    except Exception as e:
        print(f"\n💥 Test failed with error: {e}")
        import traceback
        traceback.print_exc()